### ISSUE TITLE
Реализовать компонент тегов

### ISSUE THREAD

**Issue by khakholin** [intabia-intership/wikitabia-frontend#1]
Реализовать компонент для просмотра и редактирования тегов

**Comment by Shadmer** [comment]
[Примерный макет](https://www.figma.com/file/Z9oxIueniZUvAkPeyOKXWW/Wikitabia?node-id=0%3A1)

**Comment by khakholin** [comment]
Реализовано, добавлено в проект. https://github.com/intabia-intership/wikitabia-frontend/pull/3
