### ISSUE TITLE
Реализация модального окна "Добавление/изменение тега"

### ISSUE THREAD

**Issue by Shadmer** [intabia-intership/wikitabia-frontend#8]
К статьям предусмотрена возможность добавления тегов. Для этого необходимо реализовать модальное окно с формой добавления нового тега в базу тегов. В форме должны быть:
- инпут с названием тега;
- селект с выбором цвета тега;
- кнопка добавления.

[Примерный макет](https://www.figma.com/file/Z9oxIueniZUvAkPeyOKXWW/Wikitabia?node-id=0%3A1)

**Comment by Frechet** [comment]
Ничего не понятно, что и для чего сделать то надо :)

**Comment by khakholin** [comment]
Реализовано, добавлено в проект. https://github.com/intabia-intership/wikitabia-frontend/pull/12
