### ISSUE TITLE
Реализация модального окна "Предупреждение"

### ISSUE THREAD

**Issue by Shadmer** [intabia-intership/wikitabia-frontend#9]
При удалении данных нужно предупредить пользователя с возможностью подтвердить или отменить действие.
Реализовать модальное окно, в которое входит:
- заголовок;
- текст предупреждения;
- кнопки подтверждения и отмены;

[Примерный макет](https://www.figma.com/file/Z9oxIueniZUvAkPeyOKXWW/Wikitabia?node-id=0%3A1)

**Comment by Frechet** [comment]
Огромное спасибо за макеты! Добавь мне и Александру Хахолину самые максимальные права на владение документом, пожалуйста.

**Comment by khakholin** [comment]
Реализовано, добавлено в проект. https://github.com/intabia-intership/wikitabia-frontend/pull/11
